services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.11.0 #20260322
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /opt/homepage/config:/app/config # Make sure your local config directory exists
      #- /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*" # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_VAR_PROXMOX_USERNAME: $HOMEPAGE_VAR_PROXMOX_USERNAME
      HOMEPAGE_VAR_PROXMOX_PASSWORD: $HOMEPAGE_VAR_PROXMOX_PASSWORD
      HOMEPAGE_VAR_PORTAINER_KEY: $HOMEPAGE_VAR_PORTAINER_KEY
      HOMEPAGE_VAR_GRAFANA_USERNAME: $HOMEPAGE_VAR_GRAFANA_USERNAME
      HOMEPAGE_VAR_GRAFANA_PASSWORD: $HOMEPAGE_VAR_GRAFANA_PASSWORD
