---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- WLED:
    - DigUno Living Room TV:
        - abbr: WLED
          href: http://192.168.1.127/
    - Media Stand Living Room:
        - abbr: WLED
          href: http://192.168.1.125/
    - Gledopto Bathroom Tub Niche:
        - abbr: WLED
          href: http://192.168.1.64/
    - Adesso Lamp Bedroom Master:
        - abbr: WLED
          href: http://192.168.1.174/
    - Hallway:
        - abbr: WLED
          href: http://192.168.1.79/
    - Lamp Living Room:
        - abbr: WLED
          href: http://192.168.1.160

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
        


- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
